nelmio_api_doc:
  documentation:
    info:
      title: Simple Symfony Api
      description: This is api with user management resource
      version: 1.0.0
  areas: # to filter documented areas
    path_patterns:
      - ^/api(?!/doc.json$) # Accepts routes under /api except /api/doc

  models:
    names:
      - { alias: User List, type: App\Entity\User, groups: [user_list] }
      - { alias: User Info, type: App\Entity\User, groups: [user_info] }
