#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app.swagger_ui:
  path: /doc
  methods: GET
  defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
